# Linear Regression Project Part 3 : Converting Categorical data into Numerical Data

In [6]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [7]:
df = pd.read_csv(r"D:\Python\Linear_Reg_Project_data\Ames_NO_Missing_Data.csv", keep_default_na = False)

In [8]:
pd.set_option('display.max_rows', None)
df.isnull().sum()

MS SubClass        0
MS Zoning          0
Lot Frontage       0
Lot Area           0
Street             0
Lot Shape          0
Land Contour       0
Utilities          0
Lot Config         0
Land Slope         0
Neighborhood       0
Condition 1        0
Condition 2        0
Bldg Type          0
House Style        0
Overall Qual       0
Overall Cond       0
Year Built         0
Year Remod/Add     0
Roof Style         0
Roof Matl          0
Exterior 1st       0
Exterior 2nd       0
Mas Vnr Type       0
Mas Vnr Area       0
Exter Qual         0
Exter Cond         0
Foundation         0
Bsmt Qual          0
Bsmt Cond          0
Bsmt Exposure      0
BsmtFin Type 1     0
BsmtFin SF 1       0
BsmtFin Type 2     0
BsmtFin SF 2       0
Bsmt Unf SF        0
Total Bsmt SF      0
Heating            0
Heating QC         0
Central Air        0
Electrical         0
1st Flr SF         0
2nd Flr SF         0
Low Qual Fin SF    0
Gr Liv Area        0
Bsmt Full Bath     0
Bsmt Half Bath     0
Full Bath          0
Half Bath          0
Bedroom AbvGr      0
Kitchen AbvGr      0
Kitchen Qual       0
TotRms AbvGrd      0
Functional         0
Fireplaces         0
Fireplace Qu       0
Garage Type        0
Garage Yr Blt      0
Garage Finish      0
Garage Cars        0
Garage Area        0
Garage Qual        0
Garage Cond        0
Paved Drive        0
Wood Deck SF       0
Open Porch SF      0
Enclosed Porch     0
3Ssn Porch         0
Screen Porch       0
Pool Area          0
Misc Val           0
Mo Sold            0
Yr Sold            0
Sale Type          0
Sale Condition     0
SalePrice          0
dtype: int64

## I have observed that the MS SubClass column is not a ordinal numercial type, and hence I will convert it to string

In [10]:
df['MS SubClass'] = df['MS SubClass'].apply(str)

In [11]:
# Listing down columns that are of object data type
my_object_df = df.select_dtypes(include = 'object')
my_numeric_df = df.select_dtypes(exclude = 'object')

In [12]:
# Converting them to numeric using get dummies - dtype = int will show 0 and 1 instead of True and False
df_object_dummies = pd.get_dummies(my_object_df, drop_first = True, dtype = int)

In [13]:
df_object_dummies.head()

,MS SubClass_150,MS SubClass_160,MS SubClass_180,MS SubClass_190,MS SubClass_20,MS SubClass_30,MS SubClass_40,MS SubClass_45,MS SubClass_50,MS SubClass_60,...,Sale Type_ConLw,Sale Type_New,Sale Type_Oth,Sale Type_VWD,Sale Type_WD,Sale Condition_AdjLand,Sale Condition_Alloca,Sale Condition_Family,Sale Condition_Normal,Sale Condition_Partial
0,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
1,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
2,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
3,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
4,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,1,0

In [14]:
final_df = pd.concat([my_numeric_df, df_object_dummies], axis = 1)

In [15]:
final_df.head()

,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,Bsmt Unf SF,...,Sale Type_ConLw,Sale Type_New,Sale Type_Oth,Sale Type_VWD,Sale Type_WD,Sale Condition_AdjLand,Sale Condition_Alloca,Sale Condition_Family,Sale Condition_Normal,Sale Condition_Partial
0,141.0,31770,6,5,1960,1960,112.0,639.0,0.0,441.0,...,0,0,0,0,1,0,0,0,1,0
1,80.0,11622,5,6,1961,1961,0.0,468.0,144.0,270.0,...,0,0,0,0,1,0,0,0,1,0
2,81.0,14267,6,6,1958,1958,108.0,923.0,0.0,406.0,...,0,0,0,0,1,0,0,0,1,0
3,93.0,11160,7,5,1968,1968,0.0,1065.0,0.0,1045.0,...,0,0,0,0,1,0,0,0,1,0
4,74.0,13830,5,5,1997,1998,0.0,791.0,0.0,137.0,...,0,0,0,0,1,0,0,0,1,0

In [16]:
final_df.corr()['SalePrice'].sort_values(ascending = False)

SalePrice                 1.000000
Overall Qual              0.799306
Gr Liv Area               0.706927
Garage Cars               0.647908
Garage Area               0.640397
Total Bsmt SF             0.632673
1st Flr SF                0.621711
Year Built                0.558672
Full Bath                 0.545879
Year Remod/Add            0.533295
Foundation_PConc          0.521111
Mas Vnr Area              0.502161
TotRms AbvGrd             0.495490
Fireplaces                0.474540
BsmtFin Type 1_GLQ        0.455285
Exter Qual_Gd             0.446447
Neighborhood_NridgHt      0.433275
BsmtFin SF 1              0.433208
Fireplace Qu_Gd           0.371576
MS SubClass_60            0.362276
Bsmt Exposure_Gd          0.355628
Sale Type_New             0.354257
Sale Condition_Partial    0.350088
Lot Frontage              0.348445
Garage Type_Attchd        0.345593
Exterior 1st_VinylSd      0.334546
Exterior 2nd_VinylSd      0.331277
Wood Deck SF              0.327259
Open Porch SF             0.312882
Kitchen Qual_Gd           0.304859
Mas Vnr Type_Stone        0.304253
Neighborhood_NoRidge      0.294987
Half Bath                 0.285140
Garage Cond_TA            0.276530
Roof Style_Hip            0.276463
Bsmt Full Bath            0.275742
Paved Drive_Y             0.273391
2nd Flr SF                0.269685
Lot Area                  0.266537
Central Air_Y             0.264570
Garage Qual_TA            0.255718
Garage Yr Blt             0.253709
Mas Vnr Type_BrkFace      0.246028
MS Zoning_RL              0.244173
Electrical_SBrkr          0.239939
Neighborhood_StoneBr      0.238992
Garage Type_BuiltIn       0.224199
Bsmt Qual_Gd              0.221519
House Style_2Story        0.213912
Land Contour_HLS          0.189171
Bsmt Unf SF               0.183233
Garage Finish_RFn         0.169087
Neighborhood_Somerst      0.157553
Fireplace Qu_TA           0.150915
Bedroom AbvGr             0.143952
Lot Config_CulDSac        0.143253
Exterior 1st_CemntBd      0.142061
Exterior 2nd_CmentBd      0.139122
Neighborhood_Timber       0.132003
Condition 2_PosA          0.122530
Functional_Typ            0.119400
Roof Matl_WdShngl         0.118586
Exter Cond_TA             0.117472
BsmtFin Type 2_Unf        0.113535
Screen Porch              0.112105
Bsmt Cond_TA              0.110332
MS Zoning_FV              0.106669
Condition 1_Norm          0.101385
Lot Shape_IR2             0.099659
Condition 1_PosN          0.094391
Bsmt Cond_Gd              0.088193
Neighborhood_CollgCr      0.083227
Heating_GasA              0.080024
Neighborhood_Veenker      0.076807
Condition 1_PosA          0.075882
Condition 2_PosN          0.075052
Garage Qual_Gd            0.071639
Exterior 2nd_ImStucc      0.069278
Pool Area                 0.068394
Neighborhood_Crawfor      0.063905
Land Slope_Mod            0.063547
MS SubClass_20            0.062576
Street_Pave               0.059533
Neighborhood_ClearCr      0.043056
Bldg Type_TwnhsE          0.042325
BsmtFin Type 2_GLQ        0.040392
Roof Matl_WdShake         0.040054
Lot Shape_IR3             0.038141
Mo Sold                   0.035093
Neighborhood_GrnHill      0.032457
3Ssn Porch                0.032207
Exterior 2nd_Other        0.031969
Neighborhood_Gilbert      0.030083
House Style_2.5Fin        0.025673
Land Contour_Low          0.025474
Exterior 1st_Stone        0.025422
Bsmt Exposure_Mn          0.025180
Land Slope_Sev            0.024641
Sale Type_Con             0.022588
MS SubClass_75            0.021346
Neighborhood_NWAmes       0.020575
Exterior 1st_ImStucc      0.018782
Exterior 1st_PreCast      0.018320
Exterior 2nd_PreCast      0.018320
Exterior 1st_BrkFace      0.015405
Condition 1_RRNn          0.014050
Roof Matl_Membran         0.014040
Lot Config_FR3            0.013729
Garage Cond_Gd            0.011898
Exterior 2nd_BrkFace      0.011749
Neighborhood_SawyerW      0.008615
Neighborhood_Greens       0.008333
Roof Style_Shed           0.006413
BsmtFin SF 2              0.005964
Roof Matl_Tar&Grv         0.004822
Sale Type_CWD             0.002751
Condition 2_RRAe          0.002126
Condition 1_RRAn          0.000993
Foundation_Wood           0.000046
Roof Matl_Metal          -0.000188
Sale Type_ConLI          -0.000490
House Style_2.5Unf       -0.004156
MS SubClass_150          -0.007498
Utilities_NoSeWa         -0.010020
Neighborhood_Landmrk     -0.010135
Sale Type_VWD            -0.010135
Roof Matl_Roll           -0.010135
Condition 2_RRAn         -0.010157
Roof Style_Mansard       -0.011210
Lot Config_FR2           -0.014474
Misc Val                 -0.015708
Kitchen Qual_Po          -0.016960
Heating_OthW             -0.018017
Exterior 2nd_Stone       -0.020072
MS SubClass_40           -0.020357
Sale Condition_Alloca    -0.020594
Condition 1_RRNe         -0.021695
Condition 2_Norm         -0.022199
Mas Vnr Type_CBlock      -0.023322
Foundation_Stone         -0.023845
Exterior 1st_BrkComm     -0.024564
Exterior 2nd_AsphShn     -0.026255
Heating_GasW             -0.026325
Electrical_Mix           -0.026329
Exterior 2nd_CBlock      -0.026513
House Style_1Story       -0.026729
Neighborhood_Blueste     -0.027271
Condition 2_RRNn         -0.027506
Functional_Sev           -0.027834
Fireplace Qu_Fa          -0.028515
Exterior 1st_CBlock      -0.028652
Exterior 1st_AsphShn     -0.029327
Bsmt Cond_Po             -0.029375
Yr Sold                  -0.030640
Utilities_NoSewr         -0.030922
Bsmt Qual_Po             -0.031368
MS SubClass_80           -0.032677
MS Zoning_I (all)        -0.032885
Bsmt Half Bath           -0.035864
Sale Condition_Family    -0.036878
Low Qual Fin SF          -0.037680
Sale Type_ConLw          -0.038569
Exter Cond_Po            -0.039259
BsmtFin Type 2_BLQ       -0.039688
Functional_Mod           -0.040158
BsmtFin Type 2_LwQ       -0.040318
Sale Type_Oth            -0.040371
House Style_SLvl         -0.040773
Garage Type_Basment      -0.042364
Condition 2_Feedr        -0.043247
Neighborhood_NPkVill     -0.044658
Heating QC_Po            -0.044804
Exterior 1st_Plywood     -0.045855
Roof Style_Gambrel       -0.046311
BsmtFin Type 2_Rec       -0.046567
Neighborhood_Mitchel     -0.046816
Exterior 2nd_Brk Cmn     -0.047126
Exterior 1st_Stucco      -0.047445
Garage Qual_Po           -0.047588
Functional_Sal           -0.048841
Exterior 1st_WdShing     -0.049010
MS SubClass_85           -0.050040
Exterior 2nd_Stucco      -0.051512
Condition 1_RRAe         -0.051776
MS Zoning_RH             -0.053600
Functional_Min1          -0.056041
Exterior 2nd_Wd Shng     -0.056597
Sale Condition_AdjLand   -0.057724
Heating_Wall             -0.058791
Electrical_FuseP         -0.059377
Fireplace Qu_Po          -0.061433
Functional_Maj2          -0.062331
Exter Cond_Gd            -0.063343
MS SubClass_70           -0.064602
Functional_Min2          -0.064853
Sale Type_ConLD          -0.065232
Exterior 2nd_Plywood     -0.067214
Heating_Grav             -0.067482
Garage Type_CarPort      -0.067579
MS SubClass_45           -0.067948
Roof Matl_CompShg        -0.069946
MS SubClass_180          -0.069956
Lot Config_Inside        -0.069980
House Style_1.5Unf       -0.071966
Neighborhood_SWISU       -0.073905
Garage Cond_Po           -0.074573
Land Contour_Lvl         -0.076449
House Style_SFoyer       -0.079821
BsmtFin Type 1_LwQ       -0.084399
Paved Drive_P            -0.084732
Neighborhood_BrDale      -0.095765
Exterior 2nd_HdBoard     -0.095775
MS SubClass_190          -0.100302
MS SubClass_90           -0.100910
Bldg Type_Duplex         -0.100910
Bldg Type_2fmCon         -0.101669
Overall Cond             -0.101686
Exterior 1st_HdBoard     -0.105221
Bldg Type_Twnhs          -0.106165
BsmtFin Type 1_Unf       -0.107108
Foundation_Slab          -0.114875
Condition 1_Feedr        -0.116477
MS Zoning_C (all)        -0.117327
MS SubClass_160          -0.117503
Kitchen AbvGr            -0.119857
Neighborhood_MeadowV     -0.120431
BsmtFin Type 1_BLQ       -0.122320
Electrical_FuseF         -0.123880
Exter Qual_Fa            -0.125120
Neighborhood_Sawyer      -0.128589
Enclosed Porch           -0.128629
Heating QC_Fa            -0.130434
Heating QC_Gd            -0.132062
Exterior 2nd_MetalSd     -0.134182
Neighborhood_BrkSide     -0.137297
Bsmt Cond_Fa             -0.138096
Exter Cond_Fa            -0.140293
Sale Condition_Normal    -0.141789
Exterior 1st_MetalSd     -0.144197
Kitchen Qual_Fa          -0.146719
Garage Cond_Fa           -0.147763
Bsmt Exposure_None       -0.149514
BsmtFin Type 2_None      -0.150787
BsmtFin Type 1_None      -0.154406
Bsmt Qual_None           -0.154406
Bsmt Cond_None           -0.154406
Bsmt Qual_Fa             -0.156811
BsmtFin Type 1_Rec       -0.157239
Garage Qual_Fa           -0.165800
Neighborhood_Edwards     -0.166591
Exterior 2nd_Wd Sdng     -0.167874
Exterior 1st_Wd Sdng     -0.173154
Neighborhood_IDOTRR      -0.174864
MS SubClass_50           -0.178974
Neighborhood_NAmes       -0.188727
Sale Type_WD             -0.204313
Neighborhood_OldTown     -0.212012
Garage Qual_None         -0.225723
Garage Finish_None       -0.225723
Garage Cond_None         -0.225723
Garage Type_None         -0.226005
MS SubClass_30           -0.234942
Roof Style_Gable         -0.256186
Bsmt Exposure_No         -0.282891
MS Zoning_RM             -0.292604
Lot Shape_Reg            -0.300389
Heating QC_TA            -0.338697
Foundation_CBlock        -0.349899
Garage Type_Detchd       -0.365101
Mas Vnr Type_None        -0.394694
Garage Finish_Unf        -0.422150
Bsmt Qual_TA             -0.452783
Fireplace Qu_None        -0.481444
Kitchen Qual_TA          -0.527112
Exter Qual_TA            -0.590895
Name: SalePrice, dtype: float64

In [17]:
final_df.to_csv(r"D:\Python\Linear_Reg_Project_data\AMES_Final_DF.csv")

## Final CheckPoint created, now it's time to make our model - Refer the Linear Regression Project .ipynb file